all: testLeaves testDeep testBalance

testLeaves:
	g++ -std=c++11 -o testLeaves TestLeaves.cpp

testDeep:
	g++ -std=c++11 -o testDeep TestDeep.cpp

testBalance:
	g++ -std=c++11 -o testBalance TestBalance.cpp

clean:
	rm testLeaves testDeep testBalance